org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Platform
minecraft_version=26.2
neoforge_version=26.2.0.52-beta

# Mod
mod_id=cardforge
mod_version=26.2
mod_group=org.minenite.cardforge
mod_name=Cardforge

# Paper API (matches Cardboard ver/26.2)
paper_api_version=26.2.build.110-stable
adventure_version=5.2.0
