#!/usr/bin/env python3
"""
Find the largest set of method access transformers NeoForge will accept.

NeoForge recompiles Minecraft from source, so widening a method in a
superclass is rejected when a subclass override would then be narrowed:

    ERROR getHurtSound(DamageSource) in WanderingTrader cannot override
          getHurtSound(DamageSource) in LivingEntity

The offending entry is the one on the *declaring* class (LivingEntity here),
so only that specific class+method is dropped - not every entry sharing the
method name.
"""
import re
import subprocess
import sys
from pathlib import Path

AT = Path("src/main/resources/META-INF/accesstransformer.cfg")
DISABLED = Path("src/main/resources/META-INF/accesstransformer-methods.cfg.disabled")
ROUNDS = 15

# "... in <Sub> cannot override <name>(...) in <Owner>"
ERR = re.compile(r"in \S+ cannot override (\w+)\([^)]*\) in ([\w.$]+)")


def norm(owner):
    """javac prints inner classes as Outer.Inner; ATs write them Outer$Inner."""
    return owner.replace("$", ".")


def entry_key(line):
    """('net.minecraft...LivingEntity', 'getHurtSound') for a method AT."""
    parts = line.split()
    if len(parts) < 3 or "(" not in line:
        return None
    return norm(parts[1]), parts[2].split("(")[0]


def main():
    base = [l for l in AT.read_text().splitlines() if l.strip() and "(" not in l and not l.startswith("#")]
    methods = [l for l in DISABLED.read_text().splitlines() if l.strip() and not l.startswith("#")]
    methods += [l for l in AT.read_text().splitlines() if "(" in l and not l.startswith("#")]
    methods = sorted(set(methods))
    keep = list(methods)
    print(f"starting from {len(keep)} method entries")

    for rnd in range(1, ROUNDS + 1):
        AT.write_text("# Generated by tools/aw2at.py, pruned by tools/at_prune.py\n\n"
                      + "\n".join(base + keep) + "\n")
        r = subprocess.run(["./gradlew", "createMinecraftArtifacts", "--no-daemon", "--console=plain"],
                           capture_output=True, text=True)
        if "BUILD SUCCESSFUL" in r.stdout:
            print(f"converged after {rnd} round(s): {len(keep)} of {len(methods)} method ATs apply")
            rejected = sorted(set(methods) - set(keep))
            DISABLED.write_text(
                "# Method widenings NeoForge's Minecraft recompile rejects: widening these\n"
                "# would narrow an existing subclass override. Legal under Fabric's runtime\n"
                "# bytecode widening, not in Java source. Each needs a Mixin @Invoker.\n"
                "# Regenerate with tools/at_prune.py\n\n" + "\n".join(rejected) + "\n")
            print(f"{len(rejected)} entries need @Invoker accessors")
            return 0

        bad = {(norm(owner), name) for name, owner in ERR.findall(r.stdout + r.stderr)}
        if not bad:
            print("failed for another reason:")
            for line in (r.stdout + r.stderr).splitlines():
                if "ERROR" in line or "error:" in line:
                    print("   ", line[:160])
                    break
            return 1

        before = len(keep)
        keep = [l for l in keep if entry_key(l) not in bad]
        print(f"round {rnd}: dropped {before - len(keep)} -> {len(keep)} remain")
        if before == len(keep):
            print("no progress")
            return 1
    print("did not converge")
    return 1


if __name__ == "__main__":
    sys.exit(main())
